# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger: none

stages:
  - stage: Build_Bars
    pool:
      name: 'My IBM ACE Pool'
    jobs:
      - job: Build_Bars
        workspace:
          clean: all
        steps:
          - checkout: self
          - task: Bash@3
            displayName: 'Add Libraries to Maven'
            inputs:
              targetType: 'inline'
              script: |
                cd HelloExampleJavaUtils
                mvn install:install-file -DgroupId=com.ibm.integration.test -DartifactId=integration-test -Dversion=12.0.8.0 -Dpackaging=jar -Dfile=./src/main/resources/IntegrationTest.jar
                mvn install:install-file -DgroupId=com.ibm.broker.plugin -DartifactId=jplugin2 -Dversion=12.0.8.0 -Dpackaging=jar -Dfile=./src/main/resources/jplugin2.jar
                cd ..
          - task: Bash@3
            displayName: 'Build project'
            inputs:
              targetType: 'inline'
              script: |
                export DISPLAY=:1
                Xvfb :1 > /dev/null 2>&1 &
                . /home/ivansla/Tools/ace-12.0.8.0/server/bin/mqsiprofile  
                        
                mqsicreatebar -data . -b $(Build.ArtifactStagingDirectory)/HelloExample.bar -a HelloExample -p HelloExampleJava HelloExampleJavaUtils -cleanBuild -deployAsSource
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: bars'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(Build.Repository.Name)'