# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger: none

stages:
  - stage: Build_Bars
    pool:
      name: 'My IBM ACE Pool'
    jobs:
      - job: Build_Bars
        workspace:
          clean: all
        steps:
          - checkout: self
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                export DISPLAY=:1
                Xvfb :1 > /dev/null 2>&1 &
                . /home/ivansla/Tools/ace-12.0.8.0/server/bin/mqsiprofile  
                        
                cd $(Build.Repository.Name)
                mqsicreatebar -data . -b $(Build.ArtifactStagingDirectory)/HelloExample.bar -a HelloExample -p HelloExampleJava hello-example-java-utils -cleanBuild -deployAsSource
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: bars'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(Build.Repository.Name)'