# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#

stages:
  - stage: Build_Psb_Utils
    pool:
      name: Build
      demands:
        - Agent.OS -equals Linux
    jobs:
     - job: createJar
       workspace:
         clean: all
       steps:
         - checkout: psb-utils
         - bash: |
             mvn install:install-file -DgroupId=com.ibm.broker.plugin -DartifactId=jplugin2 -Dversion=12.0.8.0 -Dpackaging=jar -Dfile=./src/main/resources/jplugin2.jar
         - task: Maven@3
           displayName: 'Maven pom.xml'
           inputs:
             goals: 'clean verify'
         - task: PublishBuildArtifacts@1
           displayName: 'Publish Artifact: psb-utils'
           inputs:
             PathtoPublish: '$(Build.SourcesDirectory)/target/build'
             ArtifactName: 'psb-utils'